# Generated by Django 4.1 on 2022-09-01 07:34

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_post_modified_post_update_alter_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update',
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
